### ISSUE TITLE
flaky test - block replicator

### ISSUE THREAD

**Issue by cendhu** [IBM-Blockchain/bcdb-server#136] opened 2021-07-28 12:46 UTC
```
closed
962
--- FAIL: TestBlockReplicator_Submit (16.95s)
963
    --- FAIL: TestBlockReplicator_Submit/normal_flow:_blocked_submit (3.01s)
964
        blockreplicator_test.go:250: 
965
            	Error Trace:	blockreplicator_test.go:250
966
            	            				asm_amd64.s:1371
967
            	Error:      	Error message not equal:
968
            	            	expected: "block replicator closed"
969
            	            	actual  : "not a leader, leader is: 0"
970
            	Test:       	TestBlockReplicator_Submit/normal_flow:_blocked_submit
971
FAIL
972
FAIL	github.com/IBM-Blockchain/bcdb-server/internal/replication	26.399s
```

**Comment by tock-ibm** [comment] 2021-08-03 08:26
Duplicate of #127

**Closed** 2021-08-04 07:09 UTC
Labels: bug
